from router.router_prompt import DEFAULT_ROUTER_RESPONSE


def map_router_to_collection(router_name: str) -> str:
    """Map router response names to actual Qdrant collection names."""
    mapping = {
        "zakon_o_radu": "zakon_o_radu",
        "zakon_o_porezu_na_dohodak_gradjana": "zakon_o_porezu_na_dohodak_gradjana", 
        "zakon_o_zastiti_podataka_o_licnosti": "zakon_o_zastiti_podataka_o_licnosti",
        "zakon_o_zastiti_potrosaca": "zakon_o_zastiti_potrosaca",
        "porodicni_zakon": "porodicni_zakon",
        "pravne_konsultacije": "pravne_konsultacije",
        "index": "index",
        "paragraf_laws": "paragraf_laws",
        "carinski_zakon": "carinski_zakon_complete",
        "krivicni_zakonik": "krivicni_zakonik",
        "zakon_o_maloletnim_uciniocima_krivicnih_dela": "zakon_o_maloletnim_uciniocima_krivicnih_dela_i_krivicnopravnoj_zastiti_maloletnih_lica",
        "zakon_o_javnim_nabavkama": "paragraf_laws",
        "ustav_republike_srbije": "ustav_republike_srbije",
        "zakon_o_privrednim_drustvima": "zakon_o_privrednim_drustvima",
        "zakon_o_bankama": "zakon_o_bankama",
        "zakon_o_narodnoj_banci_srbije": "zakon_o_narodnoj_banci_srbije",
        "zakon_o_porezu_na_dodatu_vrednost": "zakon_o_porezu_na_dodatu_vrednost",
        "zakon_o_porezu_na_dobit_pravnih_lica": "zakon_o_porezu_na_dobit_pravnih_lica",
        "zakon_o_porezima_na_imovinu": "zakon_o_porezima_na_imovinu",
        "zakon_o_porezima_na_upotrebu_drzanje_i_nosenje_dobara": "zakon_o_porezima_na_upotrebu_drzanje_i_nosenje_dobara",
        "zakon_o_planiranju_i_izgradnji": "zakon_o_planiranju_i_izgradnji",
        "zakon_o_bezbednosti_i_zdravlju_na_radu": "zakon_o_bezbednosti_i_zdravlju_na_radu",
        "zakon_o_evidencijama_u_oblasti_rada": "zakon_o_evidencijama_u_oblasti_rada",
        "zakon_o_izvrsenju_krivicnih_sankcija": "zakon_o_izvrsenju_krivicnih_sankcija",
        "zakon_o_javnim_agencijama": "zakon_o_javnim_agencijama",
        "zakon_o_javnim_medijskim_servisima": "zakon_o_javnim_medijskim_servisima",
        "zakon_o_javnim_preduzecima": "zakon_o_javnim_preduzecima",
        "zakon_o_javnim_sluzbama": "zakon_o_javnim_sluzbama",
        "zakon_o_javnim_skijalistima": "zakon_o_javnim_skijalistima",
        "zakon_o_komorama_zdravstvenih_radnika": "zakon_o_komorama_zdravstvenih_radnika",
        "zakon_o_mirnom_resavanju_radnih_sporova": "zakon_o_mirnom_resavanju_radnih_sporova",
        "zakon_o_naknadama_za_koriscenje_javnih_dobara": "zakon_o_naknadama_za_koriscenje_javnih_dobara",
        "zakon_o_posebnim_ovlascenjima_radi_efikasne_zastite_prava_intelektualne_svojine": "zakon_o_posebnim_ovlascenjima_radi_efikasne_zastite_prava_intelektualne_svojine",
        "zakon_o_saradnji_sa_medjunarodnim_krivicnim_sudom": "zakon_o_saradnji_sa_medjunarodnim_krivicnim_sudom",
        "zakon_o_sedistima_i_podrucjima_sudova_i_javnih_tuzilastava": "zakon_o_sedistima_i_podrucjima_sudova_i_javnih_tuzilastava",
        "zakon_o_uslovima_izgradnje_stanova_za_pripadnike_snaga_bezbednosti": "zakon_o_uslovima_izgradnje_stanova_za_pripadnike_snaga_bezbednosti",
        "zakon_o_uslovima_za_upucivanje_zaposlenih_na_privremeni_rad_u_inostranstvo_i_njihovoj_zastiti": "zakon_o_uslovima_za_upucivanje_zaposlenih_na_privremeni_rad_u_inostranstvo_i_njihovoj_zastiti",
        "zakon_o_platama_u_drzavnim_organima_i_javnim_sluzbama": "zakon_o_platama_u_drzavnim_organima_i_javnim_sluzbama",
        "zakon_o_privatnom_obezbedjenju": "zakon_o_privatnom_obezbedjenju",
        "zakon_o_zastiti_korisnika_finansijskih_usluga": "zakon_o_zastiti_korisnika_finansijskih_usluga",
        "pravilnik_o_aerosolnim_rasprasivacima": "paragraf_laws",
        "pravilnik_o_areometrima": "paragraf_laws",
        "zakon_o_zvanicnoj_statistici": "zakon_o_zvanicnoj_statistici",
        "zakon_o_regionalnom_razvoju": "zakon_o_regionalnom_razvoju",
        "zakon_o_glavnom_gradu": "zakon_o_glavnom_gradu",
        "sporazum_francuska_dvostruko_oporezivanje": "zakon_o_ratifikaciji_sporazuma_izmedju_socijalisticke_federativne_republike_jugoslavije_i_republike_francuske_o_izbegavanju_dvostrukog_oporezivanja_u_oblasti_poreza_na_dohodak_sa_protokolom",
        "eticki_kodeks_javnih_izvrsitelja": "eticki_kodeks_javnih_izvrsitelja",
        "porodicni_zakon": "porodicni_zakon",
        "zakon_o_osnovama_svojinskopravnih_odnosa": "zakon_o_osnovama_svojinskopravnih_odnosa",
        "dinarska_vrednost_evropskih_pragova": "dinarska_vrednost_evropskih_pragova",
        "naredba_o_merama_postupanja_u_cilju_unistavanja_unete_alohtone_divlje_vrste_heracleum_sosnowskyi": "naredba_o_merama_postupanja_u_cilju_unistavanja_unete_alohtone_divlje_vrste_heracleum_sosnowskyi",
        "nema_zakona": "nema_zakona"
    }
    return mapping.get(router_name, router_name)

